### ISSUE TITLE
Support more qualifiers in types and metas

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#80]
- [x] metas can be qualified by lidentifiers, e. g. `` `someObject.InnerClass` `` – ceylon/ceylon-spec#1243
- [x] types can be qualified with`package` – https://github.com/ceylon/ceylon-spec/issues/1245#issuecomment-77418611
- [x] metas can be qualified with `package` – ceylon/ceylon-spec#1245

**Comment by lucaswerkmeister** [comment]
Done.
