### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#9]
I want to make sure that I don’t forget to implement any AST nodes, so here’s a giant task list with all of them:
- [x] `AbstractedType` – not in `ceylon.ast`, not yet supported
- [x] `AddAssignOp` – called `AddAssignmentOperation` in `ceylon.ast`
- [x] `Alias` – split into `Alias` (abstract), `FunctionValueAlias` and `TypeAlias` in `ceylon.ast`
- [x] `AliasLiteral` – called `AliasDec` in `ceylon.ast`
- [x] `AndAssignOp` – called `AndAssignmentOperation` in `ceylon.ast`
- [x] `AndOp` – called `AndOperation` in `ceylon.ast`
- [x] `Annotation`
- [x] `AnnotationList` – called `Annotations` in `ceylon.ast`
- [x] `AnonymousAnnotation` – not in `ceylon.ast`, direct `StringLiteral` child of `Annotations`
- [x] `AnyAttribute` – called `AnyValue` in `ceylon.ast`
- [x] `AnyClass`
- [x] `AnyInterface`
- [x] `AnyMethod` – called `AnyFunction` in `ceylon.ast`
- [x] `ArgumentList` – called `Arguments` in `ceylon.ast`
- [x] `ArithmeticAssignmentOp` – called `ArithmeticAssignmentOperation` in `ceylon.ast`
- [x] `ArithmeticOp` – called `ArithmeticOperation` in `ceylon.ast`
- [x] `Assertion`
- [x] `AssignmentOp` – called `AssignmentOperation` in `ceylon.ast`
- [x] `AssignOp` – called `AssignOperation` in `ceylon.ast`
- [x] `Atom`
- [x] `AttributeArgument` – called `ValueArgument` in `ceylon.ast`
- [x] `AttributeDeclaration` – includes `ceylon.ast`’s `ValueDeclaration` and `ValueDefinition`
- [x] `AttributeGetterDefinition` – called `ValueGetterDefinition` in `ceylon.ast`
- [x] `AttributeSetterDefinition` – called `ValueSetterDefinition` in `ceylon.ast`
- [x] `BaseMemberExpression` – part of `BaseExpression` in `ceylon.ast`
- [x] `BaseMemberOrTypeExpression` – called `BaseExpression` in `ceylon.ast`
- [x] `BaseType`
- [x] `BaseTypeExpression` – part of `BaseExpression` in `ceylon.ast`
- [x] `BinaryOperatorExpression` – called `BinaryOperation` in `ceylon.ast`
- [x] `BitwiseAssignmentOp` – called `SetAssignmentOperation` in `ceylon.ast` (has nothing to do with bits!)
- [x] `BitwiseOp` – called `SetOperation` in `ceylon.ast` (has nothing to do with bits!)
- [x] `Block`
- [x] `Body`
- [x] `BooleanCondition`
- [x] `Bound`
- [x] `Break`
- [x] `CaseClause`
- [x] `CaseItem`
- [x] `CaseTypes`
- [x] `CatchClause`
- [x] `CatchVariable` – not in `ceylon.ast`, inlined into `CatchClause`
- [x] `CharLiteral`
- [x] `ClassBody`
- [x] `ClassDeclaration` – called `ClassAliasDefinition` in `ceylon.ast`
- [x] `ClassDefinition`
- [x] `ClassLiteral` – called `ClassDec` in `ceylon.ast`
- [x] `ClassOrInterface`
- [x] `ClassSpecifier`
- [x] `ClosedBound`
- [x] `CompareOp` – called `CompareOperation` in `ceylon.ast`
- [x] `ComparisonOp` – called `ComparisonOperation` in `ceylon.ast`
- [x] `CompilationUnit` – split into `AnyCompilationUnit` (abstract), `CompilationUnit`, `ModuleCompilationUnit` and `PackageCompilationUnit` in `ceylon.ast`
- [x] `CompilerAnnotation` – not in `ceylon.ast`, see #43
- [x] `ComplementAssignOp` – called `ComplementAssignmentOperation` in `ceylon.ast`
- [x] `ComplementOp` – called `ComplementOperation` in `ceylon.ast`
- [x] `Comprehension`
- [x] `ComprehensionClause`
- [x] `Condition`
- [x] `ConditionList` – called `ConditionList` in `ceylon.ast`, see #59
- [x] `Continue`
- [x] `ControlClause` – not in `ceylon.ast`
- [x] `ControlStatement` – called `ControlStructure` in `ceylon.ast`
- [x] `Declaration`
- [x] `DecrementOp` – called `PrefixDecrementOperation` in `ceylon.ast`
- [x] `DefaultedType`
- [x] `DefaultOp` – called `ElseOperation` in `ceylon.ast`
- [x] `DefaultTypeArgument` – not in `ceylon.ast` (inlined into `TypeParameter`)
- [x] `DifferenceOp` – called `DifferenceOperation` in `ceylon.ast`
- [x] `Directive`
- [x] `DivideAssignOp` – called `DivideAssignmentOperation` in `ceylon.ast`
- [x] `DocLink` – not in `ceylon.ast` (can be attached as additional information)
- [x] `Dynamic` – called `DynamicValue` in `ceylon.ast`
- [x] `DynamicClause` – not in `ceylon.ast` (inlined into `DynamicBlock`)
- [x] `DynamicModifier`
- [x] `DynamicStatement` – called `DynamicBlock` in `ceylon.ast`
- [x] `Element` – called `KeySubscript` in `ceylon.ast`
- [x] `ElementOrRange` – called `Subscript` in `ceylon.ast`, see #60
- [x] `ElementRange` – called `RangeSubscript` in `ceylon.ast`, split up into subtypes
- [x] `ElseClause` – also includes `FailClause` and `ElseCaseClause` in `ceylon.ast`
- [x] `EntryOp` – called `EntryOperation` in `ceylon.ast`
- [x] `EntryType`
- [x] `EqualityOp` – roughly corresponds to `ceylon.ast`’s `EqualityOperation`, but that also includes `IdenticalOperation`, while `IdentityOp` doesn’t extend `EqualityOp`
- [x] `EqualOp` – called `EqualOperation` in `ceylon.ast`
- [x] `ExecutableStatement` – called `Statement` in `ceylon.ast`
- [x] `Exists` – called `ExistsOperation` in `ceylon.ast`
- [x] `ExistsCondition`
- [x] `ExistsOrNonemptyCondition`
- [x] `Expression` – called `GroupedExpression` in `ceylon.ast`, at least roughly (it’s complicated)
- [x] `ExpressionComprehensionClause`
- [x] `ExpressionList` – not in `ceylon.ast`, inlined into `MatchCase`
- [x] `ExpressionStatement` – split into `ExpressionStatement` (abstract), `AssignmentStatement`, `PrefixPostfixStatement` and `InvocationStatement` in `ceylon.ast`
- [x] `ExtendedType`
- [x] `ExtendedTypeExpression` – not in `ceylon.ast`
- [x] `Extends` – not in Ceylon yet, so not in `ceylon.ast` either
- [x] `FinallyClause`
- [x] `FloatLiteral`
- [x] `ForClause`
- [x] `ForComprehensionClause`
- [x] `ForIterator`
- [x] `ForStatement` – called `ForFail` in `ceylon.ast`
- [x] `FunctionalParameterDeclaration` – called `CallableParameter` and `DefaultedCallableParameter` in `ceylon.ast`
- [x] `FunctionArgument` – called `FunctionExpression` in `ceylon.ast`
- [x] `FunctionLiteral` – called `FunctionDec` in `ceylon.ast`
- [x] `FunctionModifier`
- [x] `FunctionType` – called `CallableType` in `ceylon.ast`
- [x] `GroupedType`
- [x] `IdenticalOp` – called `IdenticalOperation` in `ceylon.ast`
- [x] `Identifier`
- [x] `IfClause`
- [x] `IfComprehensionClause`
- [x] `IfStatement` – called `IfElse` in `ceylon.ast`
- [x] `Import`
- [x] `ImportList` – not in `ceylon.ast`
- [x] `ImportMember` – called `ImportFunctionValueElement` in `ceylon.ast`
- [x] `ImportMemberOrType` – called `ImportElement` in `ceylon.ast`
- [x] `ImportMemberOrTypeList` – called `ImportElements` in `ceylon.ast`
- [x] `ImportModule` – called `ModuleImport` in `ceylon.ast`
- [x] `ImportModuleList` – called `ModuleBody` in `ceylon.ast`
- [x] `ImportPath` – called `FullPackageName` in `ceylon.ast`
- [x] `ImportType` – called `ImportTypeElement` in `ceylon.ast` (but doesn’t completely correspond, as the parser never produces it)
- [x] `ImportWildcard`
- [x] `IncrementOp` – called `PrefixIncrementOperation` in `ceylon.ast`
- [x] `IndexExpression` – called `ElementOrSubrangeExpression`
- [x] `InferredTypeArguments` – not in `ceylon.ast`
- [x] `InitialComprehensionClause`
- [x] `InitializerExpression` – not in `ceylon.ast` (not used in RedHat AST)
- [x] `InitializerParameter` – called `ParameterReference` in `ceylon.ast`, the declaration isn’t part of the initializer!
- [x] `InOp` – called `InOperation` in `ceylon.ast`
- [x] `InterfaceBody`
- [x] `InterfaceDeclaration` – called `InterfaceAliasDefinition` in `ceylon.ast`
- [x] `InterfaceDefinition` – called `AnyInterfaceDefinition` in `ceylon.ast`, includes `InterfaceDefinition` and `DynamicInterfaceDefinition` (see #57)
- [x] `InterfaceLiteral` – called `InterfaceDec` in `ceylon.ast`
- [x] `IntersectAssignOp` – called `IntersectAssignmentOperation` in `ceylon.ast`
- [x] `IntersectionOp` – called `IntersectionOperation` in `ceylon.ast`
- [x] `IntersectionType`
- [x] `InvocationExpression` – called `Invocation` in `ceylon.ast`
- [x] `IsCase`
- [x] `IsCondition`
- [x] `IsOp` – called `IsOperation` in `ceylon.ast`
- [x] `IterableType`
- [x] `KeyValueIterator`
- [x] `LargeAsOp` – called `LargeAsOperation` in `ceylon.ast`
- [x] `LargerOp` – called `LargeOperation` in `ceylon.ast`
- [x] `LazySpecifierExpression` – called `LazySpecifier` in `ceylon.ast`
- [x] `ListedArgument` – not in `ceylon.ast`
- [x] `Literal`
- [x] `LocalModifier`
- [x] `LogicalAssignmentOp` – called `LogicalAssignmentOperation` in `ceylon.ast`
- [x] `LogicalOp` – called `LogicalOperation` in `ceylon.ast`
- [x] `MatchCase`
- [x] `MemberLiteral` – covered by `ceylon.ast`’s `BaseMeta` and `MemberMeta`, and also called `MemberDec` in `ceylon.ast`
- [x] `MemberOp` – called `MemberOperator` in `ceylon.ast`
- [x] `MemberOperator` – called `AnyMemberOperator` in `ceylon.ast`
- [x] `MemberOrTypeExpression` – not in `ceylon.ast`
- [x] `MetaLiteral` – called `Meta` in `ceylon.ast`, but `Meta` is only used for meta expressions (not reference expressions)
- [x] `MethodArgument` – called `FunctionArgument` in `ceylon.ast`
- [x] `MethodDeclaration` – includes `ceylon.ast`’s `FunctionDeclaration` and `FunctionShortcutDefinition`
- [x] `MethodDefinition` – called `FunctionDefinition` in `ceylon.ast`
- [x] `MissingDeclaration` – not in `ceylon.ast`
- [x] `ModuleDescriptor`
- [x] `ModuleLiteral` – called `ModuleDec` in `ceylon.ast`
- [x] `MultiplyAssignOp` – called `MultiplyAssignmentOperation` in `ceylon.ast`
- [x] `NamedArgument`
- [x] `NamedArgumentList` – called `NamedArguments` in `ceylon.ast`
- [x] `NaturalLiteral` – called `IntegerLiteral` in `ceylon.ast`
- [x] `NegativeOp` – called `NegationOperation` in `ceylon.ast`
- [x] `Nonempty` – called `NonemptyOperation` in `ceylon.ast`
- [x] `NonemptyCondition`
- [x] `NotEqualOp` – called `NotEqualOperation` in `ceylon.ast`
- [x] `NotOp` – called `NotOperation` in `ceylon.ast`
- [x] `ObjectArgument`
- [x] `ObjectDefinition`
- [x] `OfOp` – called `OfOperation` in `ceylon.ast`
- [x] `OpenBound`
- [x] `OperatorExpression` – called `Operation` in `ceylon.ast`
- [x] `OptionalType`
- [x] `OrAssignOp` – called `OrAssignmentOperation` in `ceylon.ast`
- [x] `OrOp` – called `OrOperation` in `ceylon.ast`
- [x] `Outer`
- [x] `Package`
- [x] `PackageDescriptor`
- [x] `PackageLiteral` – called `PackageDec` in `ceylon.ast`
- [x] `Parameter`
- [x] `ParameterDeclaration` – not in `ceylon.ast`, since defaulted parameters are separate types with an abstract supertype, and we can’t split up the class hierarchy in two dimensions
- [x] `ParameterizedExpression` – not in `ceylon.ast` (artificial construct for `FunctionArgument`)
- [x] `ParameterList` – called `Parameters` in `ceylon.ast`
- [x] `PositionalArgument` – not in `ceylon.ast`. It’s the abstract supertype of `ListedArgument` (which in `ceylon.ast` is erased to `Expression`), `SpreadArgument` and `Comprehension`.
- [x] `PositionalArgumentList` – called `PositionalArguments` in `ceylon.ast`
- [x] `PositiveOp` – called `IdentityOperation` in `ceylon.ast`
- [x] `PostfixDecrementOp` – called `PostfixIncrementOperation` in `ceylon.ast`
- [x] `PostfixExpression` – will not be in `ceylon.ast`. It’s the abstract supertype of index expressions (`str[1..2]`), invocations (`fun()`) and 
- [x] `PostfixIncrementOp` – called `PostfixIncrementOperation` in `ceylon.ast`
- [x] `PostfixOperatorExpression` – called `PostfixOperation` in `ceylon.ast`
- [x] `PowerOp` – called `ExponentiationOperation` in `ceylon.ast`
- [x] `PrefixOperatorExpression` – called `PrefixOperation` in `ceylon.ast`
- [x] `Primary`
- [x] `ProductOp` – called `ProductOperation` in `ceylon.ast`
- [x] `QualifiedMemberExpression` – part of `QualifiedExpression` in `ceylon.ast`
- [x] `QualifiedMemberOrTypeExpression` – called `QualifiedExpression` in `ceylon.ast`
- [x] `QualifiedType`
- [x] `QualifiedTypeExpression` – part of `QualifiedExpression` in `ceylon.ast`
- [x] `QuotedLiteral` – not in `ceylon.ast` (relict of single-quoted 
- [x] `QuotientOp` – called `QuotientOperation` in `ceylon.ast`
- [x] `RangeOp` – called `SpanOperation` in `ceylon.ast`
- [x] `RemainderAssignOp` – called `RemainderAssignmentOperation` in `ceylon.ast`
- [x] `RemainderOp` – called `RemainderOperation` in `ceylon.ast`
- [x] `Resource`
- [x] `ResourceList` – called `Resources` in `ceylon.ast` (see #59)
- [x] `Return`
- [x] `SafeMemberOp` – called `SafeMemberOperator` in `ceylon.ast`
- [x] `SatisfiedTypes`
- [x] `Satisfies` – not in Ceylon yet, so not in `ceylon.ast` either
- [x] `SatisfiesCase` – not in Ceylon yet, so not in `ceylon.ast` either
- [x] `SatisfiesCondition` – not in Ceylon yet, so not in `ceylon.ast` either
- [x] `ScaleOp` – called `ScaleOperation` in `ceylon.ast`
- [x] `SegmentOp` – called `MeasureOperation` in `ceylon.ast`
- [x] `SelfExpression` – called `SelfReference` in `ceylon.ast`, includes `Outer` and `Package`
- [x] `SequencedArgument` – called `ArgumentList` in `ceylon.ast`
- [x] `SequencedType` – called `VariadicType` in `ceylon.ast`
- [x] `SequenceEnumeration` – called `Iterable` in `ceylon.ast`
- [x] `SequenceType` – called `SequentialType` in `ceylon.ast`
- [x] `SimpleType`
- [x] `SmallAsOp` – called `SmallAsOperation` in `ceylon.ast`
- [x] `SmallerOp` – called `SmallerOperation` in `ceylon.ast`
- [x] `SpecifiedArgument` – called `SpecifiedArgument` and `AnonymousArgument` in `ceylon.ast`
- [x] `SpecifierExpression` – called `Specifier` in `ceylon.ast`
- [x] `SpecifierOrInitializerExpression` – not in `ceylon.ast` (only used as `SpecifierExpression` in RedHat AST)
- [x] `SpecifierStatement` – called `Specification` in `ceylon.ast`
- [x] `SpreadArgument`
- [x] `SpreadOp` – called `SpreadMemberOperator` in `ceylon.ast`
- [x] `Statement` – corresponds to `Statement|Declaration` in `ceylon.ast`
- [x] `StatementOrArgument` – not in `ceylon.ast`
- [x] `StaticMemberOrTypeExpression` – not in `ceylon.ast`
- [x] `StaticType` – called `Type` in `ceylon.ast`
- [x] `StringLiteral`
- [x] `StringTemplate`
- [x] `SubtractAssignOp` – called `SubtractAssignmentOperation` in `ceylon.ast`
- [x] `SumOp` – called `SumOperation` in `ceylon.ast`
- [x] `Super`
- [x] `SuperType` – not in `ceylon.ast`
- [x] `SwitchCaseList` – called `SwitchCases` in `ceylon.ast`
- [x] `SwitchClause`
- [x] `SwitchStatement` – called `SwitchCaseElse` in `ceylon.ast`
- [x] `SyntheticVariable` – not in `ceylon.ast`
- [x] `Term` – called `Expression` in `ceylon.ast`
- [x] `ThenOp` – called `ThenOperation` in `ceylon.ast`
- [x] `This`
- [x] `Throw`
- [x] `TryCatchStatement` – called `TryCatchFinally` in `ceylon.ast`
- [x] `TryClause`
- [x] `Tuple`
- [x] `TupleType`
- [x] `Type` – called `TypeIsh` in `ceylon.ast`
- [x] `TypeAliasDeclaration` – called `TypeAliasDefinition` in `ceylon.ast`
- [x] `TypeArgumentList` – called `TypeArguments` in `ceylon.ast`
- [x] `TypeArguments` – not in `ceylon.ast` (abstract supertype of `TypeArgumentList`, `InferredTypeArguments`)
- [x] `TypeConstraint`
- [x] `TypeConstraintList` – not in `ceylon.ast`, represented as `TypeConstraint[]`
- [x] `TypedArgument` – called `InlineDefinitionArgument` in `ceylon.ast`
- [x] `TypedDeclaration`
- [x] `TypeDeclaration`
- [x] `TypeLiteral` – called `TypeMeta` in `ceylon.ast`, but also called `TypeDec` in `ceylon.ast`
- [x] `TypeOperatorExpression` – called `UnaryTypeOperation` in `ceylon.ast`
- [x] `TypeParameterDeclaration` – `TypeParameter` in `ceylon.ast`
- [x] `TypeParameterList` – called `TypeParameters` in `ceylon.ast`
- [x] `TypeParameterLiteral` – called `GivenDec` in `ceylon.ast`
- [x] `TypeSpecifier` – not in `ceylon.ast`
- [x] `TypeVariance` – called `Variance` in `ceylon.ast`
- [x] `UnaryOperatorExpression` – called `UnaryOperation` in `ceylon.ast`
- [x] `UnionAssignOp` – called `UnionAssignmentOperation` in `ceylon.ast`
- [x] `UnionOp` – called `UnionOperation` in `ceylon.ast`
- [x] `UnionType`
- [x] `ValueIterator`
- [x] `ValueLiteral` – called `ValueDec` in `ceylon.ast`
- [x] `ValueModifier`
- [x] `ValueParameterDeclaration` – called `ValueParameter` and `DefaultedValueParameter` in `ceylon.ast`
- [x] `Variable` – includes `ceylon.ast`’s `Variable` and its subtypes
- [x] `VoidModifier`
- [x] `WhileClause` – not in `ceylon.ast`
- [x] `WhileStatement` – called `While` in `ceylon.ast`
- [x] `WithinOp` – called `WithinOperation` in `ceylon.ast`
